<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<artifactId>topia-bom</artifactId>

	<parent>
		<groupId>com.godmonth.topia</groupId>
		<artifactId>topia-parent</artifactId>
		<version>1.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<packaging>pom</packaging>
	<name>topia bom</name>
	<description>topia bom</description>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-concept</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-basic</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-rpc</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-data</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-jsr303-validation</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-pagination</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.godmonth.topia</groupId>
				<artifactId>topia-idempotence</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
